server:
    port: 8081

spring:
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql : true
        hibernate-naming-physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/platosBD?createDatabaseIfNotExist=true
        username: root
        password: 949729233
eureka:
    config:
        service-url:
            defaultZone=http://localhost:8761/eureka