server:
    port: 7070
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/LourdesTenorio/proyecto.git
                    search-paths: config-data
                    default-label: master
    security:
        user:
            name: root
            password: s3cr3t
                       
                        
